name: Update NPM Dependencies

description: "Checks if there are updates to NPM packages, and creates a PR with the updated package*.json files"


inputs:
  base-branch:
    description: branch used as base for dependency update checks
    default: master
    required: false
  target-branch:
    description: branch from which PR is created
    default: update-dependencies
    required: false
  working-directory:
    description: working directory of project to check for dependency updates
    required: true
  gh-token:
    description: authentication token with repository access. must have write access to contents and pull requests
    required: true
  debug:
    description: whether to output debug messages to the console
    default: 'false'

runs:
  using: node20
  main: index.js

