name: 02 - Workflow Events

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger
        run: echo "I've been triggered by an ${{ github.event_name }}"
  
