name: 03- Workflow-Runners

on: workflow_dispatch

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show Os
        run: |
          echo "job is running on an ubuntu runner"
          echo "Runner: $RUNNER_OS"
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show win OS
        shell: bash
        run: |
          echo "job is running on windows runner"
          echo "Runner: $RUNNER_OS"
          
