name: 06-contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
env:
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRIITEN_VAR: 'workflow'
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: 'job'
      MY_OVERWRITTEN_VAR: 'job'
    steps:
      - name: display information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
      - name: Retrieve variables
        run: |
          echo "Variable value: ${{ vars.MY_VAR }}"
      - name: Working with env P-1
        env:
          MY_OVERWRITTEN_VAR: 'step'
        run: |
          echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          echo "overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
      - name: Working with env P-2
        run: |
          echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          echo "overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
