name: 17-2-custom-actions-JS
run-name: 17-2-custom-actions-JS 

on:
    workflow_dispatch:

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check for dependency updates
        uses: ./.github/actions/js-dependency-update
