name: 17-3-custom actions-Docker

on:
  workflow_dispatch:
    inputs:
      url:
        type: choice
        options
          - 'https://www.google.com'
          - 'https://www.invalid-ahfgjghvhfhjkhj.com'
          - 'invalid-jhjfddljgg'
      max-trials:
        description: Maximum trials until action fails
        default: '10'
        required: false
      delay:
        description: Delay in seconds between trials
        default: '5'
        required: false
        
  

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
          max_trails: ${{ inputs.max_trails }}
          delay: ${{ inputs.delay }}
          

  